### PR TITLE
add a title for task-schema

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by imbstack** [comment]
I wonder why the tests didn't run?

**Comment by djmitche** [comment]
503's from queue?

**Comment by djmitche** [comment]
Oh, right - 
```
Apr 26 14:28:31 taskcluster-github app/worker.1: Wed, 26 Apr 2017 19:28:31 GMT taskcluster-github:handlers:8745c300-2ab6-11e7-9469-6a4ee9da60d4 taskcluster/taskcluster-queue has no '.taskcluster.yml'. Skipping. 
```

**Comment by djmitche** [comment]
Why Travis isn't working is Not My Job™ :)

**Pull request merged**
