### PR TITLE
use res.reportError instead of res.status

### PR DESCRIPTION
**Pull request by djmitche**
This will give consistently-formatted API errors.

### CODE REVIEW

**Comment by djmitche** [comment]
I can't get the tests to run locally -- I suspect `user-config-example.yml`isn't correct?  So if this doesn't pass in travis, I may need your help.

**Comment by djmitche** [comment]
OK, Travis seemed to run this correctly, and I got the tests running locally too.  Updated version should pass.

**Comment by djmitche** [comment]
I have a taskwarrior item filed to find any stragglers in other services.  I suspect those will appear in hooks and secrets, where I seem to have made a habit of copying bad examples from other services!

**Comment by jonasfj** [comment]
I'm sure index, auth, etc. has similar legacy stuff...

**Pull request merged**
