### PR TITLE
Use the same babel-preset that we're using elsewhere

### PR DESCRIPTION
**Pull request by jhford**
We're using a really ancient version of the babel-preset.  I'm not sure why, but maybe we should update it to the latest.

### CODE REVIEW

**Comment by jonasfj** [comment]
Log from crash after we deployed this:
https://pastebin.mozilla.org/8981904

I have no idea why, it makes zero sense,, I can't reproduce locally... Or on travis.

**Comment by jonasfj** [comment]
On heroku the build was:
https://pastebin.mozilla.org/8981905

Still no idea...

**Comment by jhford** [comment]
that's usually because you're trying to run node 0.12 with a `node_modules` built with >= 4 or the other way around.  It's because 4 broke the buffer api.  Maybe we can force all the heroku caching to drop itself?

**Comment by imbstack** [comment]
I believe this failed because of issues with yarn+heroku discussed in https://github.com/heroku/heroku-buildpack-nodejs/issues/380#issue-211999514

**Comment by jhford** [comment]
@jonasfj, @imbstack do you think we can try to land this again?

**Comment by imbstack** [comment]
I think this is landed. We didn't revert it when prod broke since this didn't cause the issue.

**Pull request merged**
