### PR TITLE
Minor tweaks!

### PR DESCRIPTION
**Pull request by petemoore**
Hey Jonas,
I believe these commits fix some very minor issues.

1) For consistency I wanted to add the "object" type to list-artifacts-response.yml where it was not explicitly stated, as this was the only place where it wasn't (I only noticed when I hit a problem parsing).

2) The other tweak is adding the # character to the end of some of the Input and Output url json schema references. I haven't tested the code change, but I am hoping that will fix e.g. lines 267-268 in http://references.taskcluster.net/queue/v1/api.json:
```
267       "input": "http://schemas.taskcluster.net/queue/v1/post-artifact-request.json",
268       "output": "http://schemas.taskcluster.net/queue/v1/post-artifact-response.json"
```
to be consistent with the other references, e.g.:
```
 22       "input": "http://schemas.taskcluster.net/queue/v1/create-task-request.json#",
 23       "output": "http://schemas.taskcluster.net/queue/v1/task-status-response.json#"

 55       "input": "http://schemas.taskcluster.net/queue/v1/create-task-request.json#",
 56       "output": "http://schemas.taskcluster.net/queue/v1/task-status-response.json#"

125       "input": "http://schemas.taskcluster.net/queue/v1/task-claim-request.json#",
126       "output": "http://schemas.taskcluster.net/queue/v1/task-claim-response.json#"
```
etc...

Some of the other repos also have the missing # in places but I'll only raise PRs for those once I know if you are happy in principle with the change!
Thanks,
Pete

### CODE REVIEW

**Comment by jonasfj** [comment]
Okay, fyi, I'm merging this into my rewrite branch and merging it in that way...

If it's something you would like to see deployed soon, just say the word and I'll land it.

**Comment by jonasfj** [comment]
This will land with #32

**Comment by petemoore** [comment]
I see #32 landed yesterday; should I redeploy all schemas to get http://schemas.taskcluster.net/queue/v1/list-artifacts-response.json updated? Or are there schema updates that we want to hold off deploying at the moment?
Thanks!

**Comment by jonasfj** [comment]
@petemoore reploy what... new queue is deployed it also uploaded new schemas...
Feel free to update the go client though :)

**Comment by petemoore** [comment]
For some reason http://schemas.taskcluster.net/queue/v1/list-artifacts-response.json is still on the old version. It has not picked up the changes from commit afb497cd6486c2e4c8bae0b8f0a2550f363b50f1 - there is still a trailing " in the $schema, and the type has not been set to "object" as per this commit.

**Comment by jonasfj** [comment]
My bad feel free to make the change and land it... :)

**Pull request merged**
